action_id: trunk-single-player-auto-upgrade
date: 2025-05-06 15:14:07
run: trunk upgrade cli --single-player-only -n --no-progress --on-upgrade=false --allow-daemon-start=false
run_from: ""
trigger: schedule 24h+1h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1746544447
full_timestamp:
  nanos: 543217000
  seconds: 1746544447
trunk_version: 1.22.15
