const subcategories = [
    { id: 1, name: 'Food', category_id: 1 },
    { id: 2, name: 'Drinks', category_id: 1 },
    { id: 3, name: 'Cosmetic Packages', category_id: 2 },
    { id: 4, name: 'Hair Care', category_id: 2 },
    { id: 5, name: 'Skin Care', category_id: 2 },
    { id: 6, name: 'Makeup', category_id: 2 },
    { id: 7, name: 'Manicure and Pedicure', category_id: 2 },
    { id: 8, name: 'Bath and Personal Hygiene', category_id: 2 },
    { id: 9, name: 'Perfumes and Fragrances', category_id: 2 },
    { id: 10, name: 'DIY Tools', category_id: 3 },
    { id: 11, name: 'Smart Home', category_id: 3 },
    { id: 12, name: 'Gardening Tools', category_id: 3 },
    { id: 13, name: 'Electrical Installation', category_id: 3 },
    { id: 14, name: 'Bathroom and Kitchen Plumbing', category_id: 3 },
    { id: 15, name: 'Safety and Prevention', category_id: 3 },
    { id: 16, name: 'Movies', category_id: 4 },
    { id: 17, name: 'TV Series', category_id: 4 },
    { id: 18, name: 'Blu-ray', category_id: 4 },
    { id: 19, name: 'CDs and Vinyl', category_id: 4 },
    { id: 20, name: 'Digital Music', category_id: 4 },
    { id: 21, name: 'Musical Instruments', category_id: 4 },
    { id: 22, name: 'Car Accessories and Parts', category_id: 5 },
    { id: 23, name: 'Tools and Equipment', category_id: 5 },
    { id: 24, name: 'GPS', category_id: 5 },
    { id: 25, name: 'Motorcycle Accessories and Parts', category_id: 5 },
    { id: 26, name: 'Running', category_id: 6 },
    { id: 27, name: 'Fitness and Exercise', category_id: 6 },
    { id: 28, name: 'Cycling', category_id: 6 },
    { id: 29, name: 'Tennis and Paddle', category_id: 6 },
    { id: 30, name: 'Golf', category_id: 6 },
    { id: 31, name: 'Team Sports', category_id: 6 },
    { id: 32, name: 'Water Sports', category_id: 6 },
    { id: 33, name: 'Winter Sports', category_id: 6 },
    { id: 34, name: 'Camping and Hiking', category_id: 6 },
    { id: 35, name: 'Yoga', category_id: 6 },
    { id: 36, name: 'Urban Mobility', category_id: 6 },
    { id: 37, name: 'GPS and Electronics', category_id: 6 },
    { id: 38, name: 'Photography and Camcorders', category_id: 7 },
    { id: 39, name: 'Mobile Phones and Telephony', category_id: 7 },
    { id: 40, name: 'TV, Video, and Home Cinema', category_id: 7 },
    { id: 41, name: 'Audio and Hi-Fi', category_id: 7 },
    { id: 42, name: 'GPS', category_id: 7 },
    { id: 43, name: 'Musical Instruments', category_id: 7 },
    { id: 44, name: 'Accessories', category_id: 7 },
    { id: 45, name: 'Smart Home', category_id: 7 },
    { id: 46, name: 'Kitchen', category_id: 8 },
    { id: 47, name: 'Dining Room and/or Living Room', category_id: 8 },
    { id: 48, name: 'Bedroom', category_id: 8 },
    { id: 49, name: 'Bathroom', category_id: 8 },
    { id: 50, name: 'Garden', category_id: 8 },
    { id: 51, name: 'Lighting', category_id: 8 },
    { id: 52, name: 'Small Appliances', category_id: 8 },
    { id: 53, name: 'Vacuuming, Cleaning, and Ironing', category_id: 8 },
    { id: 54, name: 'Storage and Organization', category_id: 8 },
    { id: 55, name: 'Climate Control and Heating', category_id: 8 },
    { id: 56, name: 'Large Appliances', category_id: 8 },
    { id: 57, name: 'Smart Home', category_id: 8 },
    { id: 58, name: 'Electrical Installation', category_id: 8 },
    { id: 59, name: 'Bathroom and Kitchen Plumbing', category_id: 8 },
    { id: 60, name: 'Safety and Prevention', category_id: 8 },
    { id: 61, name: 'Laptops', category_id: 9 },
    { id: 62, name: 'Tablets', category_id: 9 },
    { id: 63, name: 'Desktops', category_id: 9 },
    { id: 64, name: 'Monitors', category_id: 9 },
    { id: 65, name: 'Components', category_id: 9 },
    { id: 66, name: 'Accessories', category_id: 9 },
    { id: 67, name: 'Printers and Ink', category_id: 9 },
    { id: 68, name: 'Software', category_id: 9 },
    { id: 69, name: 'Gaming', category_id: 9 },
    { id: 70, name: 'Paper', category_id: 9 },
    { id: 71, name: 'Pens and Writing Supplies', category_id: 9 },
    { id: 72, name: 'Office Electronics', category_id: 9 },
    { id: 73, name: 'Toys', category_id: 10 },
    { id: 74, name: 'Games', category_id: 10 },
    { id: 75, name: 'Books', category_id: 11 },
    { id: 76, name: 'eBooks', category_id: 11 },
    { id: 77, name: 'Audiobooks', category_id: 11 },
    { id: 78, name: 'Office Supplies', category_id: 12 },
    { id: 79, name: 'Paper', category_id: 12 },
    { id: 80, name: 'Pens and Writing Supplies', category_id: 12 },
    { id: 81, name: 'Office Electronics', category_id: 12 },
    { id: 82, name: 'Clothing', category_id: 13 },
    { id: 83, name: 'Shoes', category_id: 13 },
    { id: 84, name: 'Jewelry', category_id: 13 },
    { id: 85, name: 'Accessories', category_id: 13 },
    { id: 86, name: 'Consoles and Accessories', category_id: 14 },
    { id: 87, name: 'PC Games', category_id: 14 },
    { id: 88, name: 'Merchandising', category_id: 14 },
    { id: 89, name: 'Kids', category_id: 14 },
];
const materials = [
    { id: 1, name: 'Leather' },
    { id: 2, name: 'Cotton' },
    { id: 3, name: 'Wood' },
    { id: 4, name: 'Stainless Steel' },
    { id: 5, name: 'Plastic' },
    { id: 6, name: 'Glass' },
    { id: 7, name: 'Ceramic' },
    { id: 8, name: 'Canvas' },
    { id: 9, name: 'Polyester' },
    { id: 10, name: 'Silk' },
];
const targets = [
    { id: 1, name: 'Men' },
    { id: 2, name: 'Women' },
    { id: 3, name: 'Unisex' },
    { id: 4, name: 'Kids' },
    { id: 5, name: 'Teens' },
    { id: 6, name: 'Adults' },
    { id: 7, name: 'Seniors' },
    { id: 8, name: 'Pets' },
];
const colors = [
    { id: 1, name: 'Black' },
    { id: 2, name: 'White' },
    { id: 3, name: 'Red' },
    { id: 4, name: 'Blue' },
    { id: 5, name: 'Green' },
    { id: 6, name: 'Yellow' },
    { id: 7, name: 'Pink' },
    { id: 8, name: 'Grey' },
    { id: 9, name: 'Brown' },
    { id: 10, name: 'Purple' },
    { id: 11, name: 'Orange' },
    { id: 12, name: 'Beige' },
    { id: 13, name: 'Silver' },
    { id: 14, name: 'Gold' },
    { id: 15, name: 'Multicolor' },
];
const shops = [
    {
        id: 3,
        name: 'TechZone',
        description: 'Tienda especializada en productos electrónicos y gadgets innovadores.',
        direction: 'Calle Innovación 123, Madrid',
        phone_number: '911 234 567',
        email: 'contacto@techzone.com',
        postal_code: '28001',
        created_at: '2025-04-30T16:21:49.809821',
        creator: '19495d25-05ae-4f81-9e69-d8761ac69de6',
    },
    {
        id: 4,
        name: 'EcoMarket',
        description: 'Tienda de productos sostenibles, ecológicos y de comercio justo.',
        direction: 'Avenida Verde 456, Barcelona',
        phone_number: '933 456 789',
        email: 'info@ecomarket.es',
        postal_code: '08002',
        created_at: '2025-04-30T16:21:49.809821',
        creator: '783bde3a-6228-49f2-bc77-af76e3056143',
    },
    {
        id: 5,
        name: 'Gourmet Delicias',
        description: 'Tienda de alimentos gourmet y vinos exclusivos.',
        direction: 'Calle Sabores 12, Sevilla',
        phone_number: '955 123 456',
        email: 'contacto@gourmetdelicias.es',
        postal_code: '41001',
        created_at: '2025-04-30T16:29:43.506105',
        creator: '42f79a11-8645-4f27-98cb-cb681229f626',
    },
    {
        id: 6,
        name: 'UrbanWear',
        description: 'Ropa urbana y accesorios de moda contemporánea.',
        direction: 'Calle Estilo 9, Valencia',
        phone_number: '961 234 789',
        email: 'info@urbanwear.com',
        postal_code: '46002',
        created_at: '2025-04-30T16:29:43.506105',
        creator: '783bde3a-6228-49f2-bc77-af76e3056143',
    },
    {
        id: 7,
        name: 'BioSalud',
        description: 'Productos naturales, suplementos y artículos de salud.',
        direction: 'Paseo Vital 88, Zaragoza',
        phone_number: '976 789 321',
        email: 'ventas@biosalud.es',
        postal_code: '50003',
        created_at: '2025-04-30T16:29:43.506105',
        creator: '42f79a11-8645-4f27-98cb-cb681229f626',
    },
    {
        id: 8,
        name: 'Libros & Café',
        description: 'Librería con cafetería y eventos culturales.',
        direction: 'Calle Lectura 27, Bilbao',
        phone_number: '944 567 890',
        email: 'hola@librosycafe.com',
        postal_code: '48001',
        created_at: '2025-04-30T16:29:43.506105',
        creator: '783bde3a-6228-49f2-bc77-af76e3056143',
    },
    {
        id: 9,
        name: 'TecnoHogar',
        description: 'Electrodomésticos y soluciones inteligentes para el hogar.',
        direction: 'Av. Tecnología 101, Málaga',
        phone_number: '952 345 678',
        email: 'atencion@tecnohogar.es',
        postal_code: '29004',
        created_at: '2025-04-30T16:29:43.506105',
        creator: '783bde3a-6228-49f2-bc77-af76e3056143',
    },
    {
        id: 10,
        name: 'PetManía',
        description: 'Tienda para mascotas con accesorios y alimentos premium.',
        direction: 'Calle Animal 5, Alicante',
        phone_number: '965 222 333',
        email: 'soporte@petmania.com',
        postal_code: '03001',
        created_at: '2025-04-30T16:29:43.506105',
        creator: '42f79a11-8645-4f27-98cb-cb681229f626',
    },
    {
        id: 11,
        name: 'Juguetelandia',
        description: 'Juguetes educativos y de entretenimiento para niños.',
        direction: 'Plaza Juegos 17, Granada',
        phone_number: '958 456 789',
        email: 'info@juguetelandia.es',
        postal_code: '18001',
        created_at: '2025-04-30T16:29:43.506105',
        creator: '19495d25-05ae-4f81-9e69-d8761ac69de6',
    },
    {
        id: 12,
        name: 'ModaEco',
        description: 'Moda sostenible y ropa reciclada.',
        direction: 'Av. Moda 23, Valladolid',
        phone_number: '983 123 456',
        email: 'moda@modaeco.com',
        postal_code: '47001',
        created_at: '2025-04-30T16:29:43.506105',
        creator: '783bde3a-6228-49f2-bc77-af76e3056143',
    },
    {
        id: 13,
        name: 'ArteLocal',
        description: 'Galería y tienda de arte de artistas locales.',
        direction: 'Calle Cultura 3, Santander',
        phone_number: '942 456 123',
        email: 'contacto@artelocal.es',
        postal_code: '39001',
        created_at: '2025-04-30T16:29:43.506105',
        creator: '19495d25-05ae-4f81-9e69-d8761ac69de6',
    },
    {
        id: 14,
        name: 'FitZone',
        description: 'Artículos deportivos y ropa de entrenamiento.',
        direction: 'Ronda Fitness 66, Murcia',
        phone_number: '968 765 432',
        email: 'ventas@fitzone.com',
        postal_code: '30004',
        created_at: '2025-04-30T16:29:43.506105',
        creator: '42f79a11-8645-4f27-98cb-cb681229f626',
    },
];
const sizes = [
    { id: 1, name: 'Small' },
    { id: 2, name: 'Medium' },
    { id: 3, name: 'Large' },
    { id: 4, name: 'X-Large' },
    { id: 5, name: 'XX-Large' },
    { id: 6, name: 'One Size' },
    { id: 7, name: 'Plus Size' },
    { id: 8, name: 'Petite' },
    { id: 9, name: 'Kids' },
    { id: 10, name: 'Baby' },
    { id: 11, name: 'Toddler' },
];
const conditions = [
    { id: 1, name: 'New' },
    { id: 2, name: 'Used' },
    { id: 3, name: 'Refurbished' },
    { id: 4, name: 'Pre-owned' },
    { id: 5, name: 'Open Box' },
    { id: 6, name: 'Vintage' },
    { id: 7, name: 'Antique' },
];
const sources = [
    { id: 1, name: 'Organic' },
    { id: 2, name: 'Fair-trade Certified' },
    { id: 3, name: 'Imported' },
    { id: 4, name: 'Locally Sourced' },
    { id: 5, name: 'Handcrafted' },
    { id: 6, name: 'Eco-conscious' },
];

const sustainability = [
    { id: 1, name: 'Recycled' },
    { id: 2, name: 'Biodegradable' },
    { id: 3, name: 'Zero Waste' },
    { id: 4, name: 'Sustainable Materials' },
    { id: 5, name: 'Reusable' },
    { id: 6, name: 'Plastic-free' },
    { id: 7, name: 'Carbon-neutral' },
    { id: 8, name: 'Fair Trade' },
    { id: 9, name: 'Eco-friendly Packaging' },
    { id: 10, name: 'Non-toxic' },
];

const users = [
    { uuid: '19495d25-05ae-4f81-9e69-d8761ac69de6', email: 'oriolmorell03@gmail.com' },
    { uuid: '42f79a11-8645-4f27-98cb-cb681229f626', email: 'cesar.lira@outlook.com' },
    { uuid: '783bde3a-6228-49f2-bc77-af76e3056143', email: 'gerard.vello@gmail.com' },
];

const products = {
    1: {
        id: 1,
        title: 'Smartphone XYZ',
        stock: 50,
        images: {
            thumbnail: 'https://example.com/image1.jpg',
            full: ['https://example.com/image1_full.jpg', 'https://example.com/image1_full2.jpg'],
        },
        color: 1,
        size: 2,
        description: 'Latest model with advanced features.',
        price: 699.99,
        shop: 3,
    },
    // Add more products as needed
};

const multiple_categorys = ['category', 'condition', 'material', 'source', 'sustainability', 'target'];
