@echo off
REM Generated by trunk tool 'checkov'
set PYTHONUTF8=1
set HOME=%HOME%
if not defined HOME set HOME=
set PATH=C:\Users\Cesar\AppData\Local\trunk\tools\checkov\3.2.416-8b5d848f9b2f3d26e3af3ce0fff8dc62/bin;C:\Users\Cesar\AppData\Local\trunk\tools\checkov\3.2.416-8b5d848f9b2f3d26e3af3ce0fff8dc62/Scripts;C:\Users\Cesar\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070/bin;C:\Users\Cesar\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070;C:\Users\Cesar\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\Cesar\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%
set VIRTUAL_ENV=C:\Users\Cesar\AppData\Local\trunk\tools\checkov\3.2.416-8b5d848f9b2f3d26e3af3ce0fff8dc62

start /w /b checkov %*
