@echo off
REM Generated by trunk tool 'markdownlint'
set NODE_PATH=C:\Users\Cesar\AppData\Local\trunk\tools\markdownlint\0.44.0-5a8bda93feea4dc5a41c715df34108d4/node_modules
set HOME=%HOME%
if not defined HOME set HOME=
set PATH=C:\Users\Cesar\AppData\Local\trunk\tools\markdownlint\0.44.0-5a8bda93feea4dc5a41c715df34108d4/node_modules/.bin;C:\Users\Cesar\AppData\Local\trunk\tools\node\18.20.5-730a53566ca346270d1e9ab4c1afaea8/bin;C:\Users\Cesar\AppData\Local\trunk\tools\node\18.20.5-730a53566ca346270d1e9ab4c1afaea8;C:\Users\Cesar\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\Cesar\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b markdownlint %*
