@echo off
REM Generated by trunk tool 'osv-scanner'
set PATH=C:\Users\Cesar\AppData\Local\trunk\tools\osv-scanner\2.0.2-7f223bce81cb208c2024f8e19a30f3df;C:\Users\Cesar\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\Cesar\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b osv-scanner %*
