@echo off
REM Generated by trunk tool 'svgo'
set HOME=%HOME%
if not defined HOME set HOME=
set PATH=C:\Users\Cesar\AppData\Local\trunk\tools\svgo\3.3.2-266d0518ddc88a894e3ffdda3af9dbd1/node_modules/.bin;C:\Users\Cesar\AppData\Local\trunk\tools\node\18.20.5-730a53566ca346270d1e9ab4c1afaea8/bin;C:\Users\Cesar\AppData\Local\trunk\tools\node\18.20.5-730a53566ca346270d1e9ab4c1afaea8;C:\Users\Cesar\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\Cesar\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%
set NODE_PATH=C:\Users\Cesar\AppData\Local\trunk\tools\svgo\3.3.2-266d0518ddc88a894e3ffdda3af9dbd1/node_modules

start /w /b svgo %*
