@echo off
REM Generated by trunk tool 'trufflehog'
set PATH=C:\Users\Cesar\AppData\Local\trunk\tools\trufflehog\3.88.28-e69e47ce0b9e67f4baad0d2511816187;C:\Users\Cesar\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\Cesar\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b trufflehog %*
