@echo off
REM Generated by trunk tool 'yamllint'
set PYTHONUTF8=1
set HOME=%HOME%
if not defined HOME set HOME=
set PATH=C:\Users\Cesar\AppData\Local\trunk\tools\yamllint\1.37.1-81b31ef352a9ce5644e1b429a68d81fd/bin;C:\Users\Cesar\AppData\Local\trunk\tools\yamllint\1.37.1-81b31ef352a9ce5644e1b429a68d81fd/Scripts;C:\Users\Cesar\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070/bin;C:\Users\Cesar\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070;C:\Users\Cesar\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\Cesar\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%
set VIRTUAL_ENV=C:\Users\Cesar\AppData\Local\trunk\tools\yamllint\1.37.1-81b31ef352a9ce5644e1b429a68d81fd

start /w /b yamllint %*
