action_id: trunk-whoami
date: 2025-05-07 11:29:35
run: trunk whoami
run_from: ""
trigger: schedule 24h+1h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-whoami'. See .trunk\out\6OFpB.yaml for details.
  error_path: C:\Users\Cesar\OneDrive\Escritorio\CursoBoothCamp\MarketPlace\.trunk\out\6OFpB.yaml
timestamp: 1746617375
full_timestamp:
  nanos: 834769000
  seconds: 1746617375
trunk_version: 1.22.15
