action_id: trunk-upgrade-available
date: 2025-05-06 19:29:22
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 0
  out: "notifications_to_delete:\r\n  - trunk-check-upgrade\r\n  - trunk-upgrade\r\n"
  err: ""
timestamp: 1746559762
full_timestamp:
  nanos: 862129000
  seconds: 1746559762
trunk_version: 1.22.15
action_output:
  notifications_to_delete:
    - trunk-check-upgrade
    - trunk-upgrade
