action_id: trunk-upgrade-available
date: 2025-05-06 14:18:25
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: .trunk/trunk.yaml
result:
  exit_code: 0
  out: "notifications_to_delete:\r\n  - trunk-check-upgrade\r\n  - trunk-upgrade\r\n"
  err: ""
timestamp: 1746541105
full_timestamp:
  nanos: 977968000
  seconds: 1746541105
trunk_version: 1.22.15
action_output:
  notifications_to_delete:
    - trunk-check-upgrade
    - trunk-upgrade
