action_id: trunk-upgrade-available
date: 2025-05-07 12:29:35
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-upgrade-available'. See .trunk\out\xugyG.yaml for details.
  error_path: C:\Users\Cesar\OneDrive\Escritorio\CursoBoothCamp\MarketPlace\.trunk\out\xugyG.yaml
timestamp: 1746620975
full_timestamp:
  nanos: 835000000
  seconds: 1746620975
trunk_version: 1.22.15
